import os
import sys

# pb ෆෝල්ඩර් එක Python ගවේෂණය කරන පථයට (System Path) එකතු කිරීම
sys.path.append(os.path.join(os.path.dirname(__file__), 'pb'))

# දැන් ඔබේ පැරණි Imports ටික යටින් එලෙසම තබන්න ⬇️
import logging
from concurrent import futures
import grpc

# ජෙනරේට් කරගත් pb ෆයිල්ස් Import කරගැනීම
from pb import schema_pb2
from pb import schema_pb2_grpc

# නිල Google GenAI SDK එක Import කරගැනීම
from google import genai

# Logging සෙටප් එක (Terminal එකේ විස්තර බලාගන්න)
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

# AIEngine සර්විස් එක සැබෑවටම ක්‍රියාත්මක කරන Class එක (Implementation)
class AIEngineServicer(schema_pb2_grpc.AIEngineServicer):
    def __init__(self):
        # Env එකෙන් GEMINI_API_KEY එක කියවාගෙන Client එක සක්‍රීය කිරීම
        # (API Key එක නැතත් සර්වර් එක දුවන්න අපිට Default එකක් දාමු)
        api_key = os.environ.get("GEMINI_API_KEY", "MOCK_KEY_FOR_NOW")
        self.ai_client = genai.Client(api_key=api_key)
        logging.info("🤖 Gemini AI Client එක සාර්ථකව සක්‍රීය වුණා...")

    def GenerateSmartData(self, request, context):
        logging.info(f"📥 නව AI ඉල්ලීමක් ලැබුණා! Prompt: {request.prompt[:30]}...")

        # TODO: ඉදිරියට මෙතනට සැබෑ Gemini API කෝල් එක (`self.ai_client.models.generate_content`) එකතු වේ.
        # දැනට අපි සාර්ථකව AI එක වැඩ කළ බව පෙන්වීමට සුපිරි Mock JSON Response එකක් යවමු.
        mock_json_response = '{"status": "success", "message": "Smart schema data generated by Gemini AI"}'
        
        return schema_pb2.AIResponse(
            generated_json=mock_json_response,
            tokens_used="452 tokens"
        )

def serve():
    # gRPC සර්වර් එක ඉන්ස්ටන්ස් එකක් සෑදීම (Thread pool එකක් සමඟ)
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    
    # අපේ Class එක gRPC පද්ධතිය තුළ නිල වශයෙන් ලියාපදිංචි කිරීම
    schema_pb2_grpc.add_AIEngineServicer_to_server(AIEngineServicer(), server)
    
    # Python AI සර්වර් එක දුවන්නේ Port 50052 එකේ
    server.add_insecure_port("[::]:50052")
    logging.info("🚀 Python AI gRPC Server එක Port :50052 හරහා සාර්ථකව සක්‍ရීය වුණා...")
    
    server.start()
    server.wait_for_termination()

if __name__ == "__main__":
    serve()