# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import schema_pb2 as schema__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in schema_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataProcessorStub:
    """1. GO WORKER SERVICE: ලොකු ෆයිල්ස් ප්‍රොසෙස් කරන සේවාව
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessCSV = channel.unary_unary(
                '/saas.DataProcessor/ProcessCSV',
                request_serializer=schema__pb2.FileRequest.SerializeToString,
                response_deserializer=schema__pb2.JobResponse.FromString,
                _registered_method=True)


class DataProcessorServicer:
    """1. GO WORKER SERVICE: ලොකු ෆයිල්ස් ප්‍රොසෙස් කරන සේවාව
    """

    def ProcessCSV(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessCSV': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessCSV,
                    request_deserializer=schema__pb2.FileRequest.FromString,
                    response_serializer=schema__pb2.JobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'saas.DataProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('saas.DataProcessor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataProcessor:
    """1. GO WORKER SERVICE: ලොකු ෆයිල්ස් ප්‍රොසෙස් කරන සේවාව
    """

    @staticmethod
    def ProcessCSV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saas.DataProcessor/ProcessCSV',
            schema__pb2.FileRequest.SerializeToString,
            schema__pb2.JobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AIEngineStub:
    """2. PYTHON AI SERVICE: Gemini AI කනෙක්ෂන් එක හසුරුවන සේවාව
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateSmartData = channel.unary_unary(
                '/saas.AIEngine/GenerateSmartData',
                request_serializer=schema__pb2.PromptRequest.SerializeToString,
                response_deserializer=schema__pb2.AIResponse.FromString,
                _registered_method=True)


class AIEngineServicer:
    """2. PYTHON AI SERVICE: Gemini AI කනෙක්ෂන් එක හසුරුවන සේවාව
    """

    def GenerateSmartData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateSmartData': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSmartData,
                    request_deserializer=schema__pb2.PromptRequest.FromString,
                    response_serializer=schema__pb2.AIResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'saas.AIEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('saas.AIEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIEngine:
    """2. PYTHON AI SERVICE: Gemini AI කනෙක්ෂන් එක හසුරුවන සේවාව
    """

    @staticmethod
    def GenerateSmartData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/saas.AIEngine/GenerateSmartData',
            schema__pb2.PromptRequest.SerializeToString,
            schema__pb2.AIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
