# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\x12\x04saas\"1\n\x0b\x46ileRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\"H\n\x0bJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x19\n\x11records_processed\x18\x03 \x01(\x05\"7\n\rPromptRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x16\n\x0e\x63ontext_schema\x18\x02 \x01(\t\"9\n\nAIResponse\x12\x16\n\x0egenerated_json\x18\x01 \x01(\t\x12\x13\n\x0btokens_used\x18\x02 \x01(\t2C\n\rDataProcessor\x12\x32\n\nProcessCSV\x12\x11.saas.FileRequest\x1a\x11.saas.JobResponse2F\n\x08\x41IEngine\x12:\n\x11GenerateSmartData\x12\x13.saas.PromptRequest\x1a\x10.saas.AIResponseB\x0eZ\x0cgo-worker/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014go-worker/pb'
  _globals['_FILEREQUEST']._serialized_start=22
  _globals['_FILEREQUEST']._serialized_end=71
  _globals['_JOBRESPONSE']._serialized_start=73
  _globals['_JOBRESPONSE']._serialized_end=145
  _globals['_PROMPTREQUEST']._serialized_start=147
  _globals['_PROMPTREQUEST']._serialized_end=202
  _globals['_AIRESPONSE']._serialized_start=204
  _globals['_AIRESPONSE']._serialized_end=261
  _globals['_DATAPROCESSOR']._serialized_start=263
  _globals['_DATAPROCESSOR']._serialized_end=330
  _globals['_AIENGINE']._serialized_start=332
  _globals['_AIENGINE']._serialized_end=402
# @@protoc_insertion_point(module_scope)
