// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/schema.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataProcessor_ProcessCSV_FullMethodName = "/saas.DataProcessor/ProcessCSV"
)

// DataProcessorClient is the client API for DataProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 1. GO WORKER SERVICE: ලොකු ෆයිල්ස් ප්‍රොසෙස් කරන සේවාව
type DataProcessorClient interface {
	ProcessCSV(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*JobResponse, error)
}

type dataProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewDataProcessorClient(cc grpc.ClientConnInterface) DataProcessorClient {
	return &dataProcessorClient{cc}
}

func (c *dataProcessorClient) ProcessCSV(ctx context.Context, in *FileRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, DataProcessor_ProcessCSV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataProcessorServer is the server API for DataProcessor service.
// All implementations must embed UnimplementedDataProcessorServer
// for forward compatibility.
//
// 1. GO WORKER SERVICE: ලොකු ෆයිල්ස් ප්‍රොසෙස් කරන සේවාව
type DataProcessorServer interface {
	ProcessCSV(context.Context, *FileRequest) (*JobResponse, error)
	mustEmbedUnimplementedDataProcessorServer()
}

// UnimplementedDataProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataProcessorServer struct{}

func (UnimplementedDataProcessorServer) ProcessCSV(context.Context, *FileRequest) (*JobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessCSV not implemented")
}
func (UnimplementedDataProcessorServer) mustEmbedUnimplementedDataProcessorServer() {}
func (UnimplementedDataProcessorServer) testEmbeddedByValue()                       {}

// UnsafeDataProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataProcessorServer will
// result in compilation errors.
type UnsafeDataProcessorServer interface {
	mustEmbedUnimplementedDataProcessorServer()
}

func RegisterDataProcessorServer(s grpc.ServiceRegistrar, srv DataProcessorServer) {
	// If the following call panics, it indicates UnimplementedDataProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataProcessor_ServiceDesc, srv)
}

func _DataProcessor_ProcessCSV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataProcessorServer).ProcessCSV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataProcessor_ProcessCSV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataProcessorServer).ProcessCSV(ctx, req.(*FileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataProcessor_ServiceDesc is the grpc.ServiceDesc for DataProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saas.DataProcessor",
	HandlerType: (*DataProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessCSV",
			Handler:    _DataProcessor_ProcessCSV_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/schema.proto",
}

const (
	AIEngine_GenerateSmartData_FullMethodName = "/saas.AIEngine/GenerateSmartData"
)

// AIEngineClient is the client API for AIEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 2. PYTHON AI SERVICE: Gemini AI කනෙක්ෂන් එක හසුරුවන සේවාව
type AIEngineClient interface {
	GenerateSmartData(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (*AIResponse, error)
}

type aIEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewAIEngineClient(cc grpc.ClientConnInterface) AIEngineClient {
	return &aIEngineClient{cc}
}

func (c *aIEngineClient) GenerateSmartData(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (*AIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIResponse)
	err := c.cc.Invoke(ctx, AIEngine_GenerateSmartData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIEngineServer is the server API for AIEngine service.
// All implementations must embed UnimplementedAIEngineServer
// for forward compatibility.
//
// 2. PYTHON AI SERVICE: Gemini AI කනෙක්ෂන් එක හසුරුවන සේවාව
type AIEngineServer interface {
	GenerateSmartData(context.Context, *PromptRequest) (*AIResponse, error)
	mustEmbedUnimplementedAIEngineServer()
}

// UnimplementedAIEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIEngineServer struct{}

func (UnimplementedAIEngineServer) GenerateSmartData(context.Context, *PromptRequest) (*AIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateSmartData not implemented")
}
func (UnimplementedAIEngineServer) mustEmbedUnimplementedAIEngineServer() {}
func (UnimplementedAIEngineServer) testEmbeddedByValue()                  {}

// UnsafeAIEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIEngineServer will
// result in compilation errors.
type UnsafeAIEngineServer interface {
	mustEmbedUnimplementedAIEngineServer()
}

func RegisterAIEngineServer(s grpc.ServiceRegistrar, srv AIEngineServer) {
	// If the following call panics, it indicates UnimplementedAIEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIEngine_ServiceDesc, srv)
}

func _AIEngine_GenerateSmartData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIEngineServer).GenerateSmartData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIEngine_GenerateSmartData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIEngineServer).GenerateSmartData(ctx, req.(*PromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIEngine_ServiceDesc is the grpc.ServiceDesc for AIEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saas.AIEngine",
	HandlerType: (*AIEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateSmartData",
			Handler:    _AIEngine_GenerateSmartData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/schema.proto",
}
